USE SCHEMA {{target_schema}};


CREATE OR REPLACE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);


CREATE OR REPLACE TABLE DIM_DATE 
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM;

